### ISSUE TITLE
Doesn't work in Discord

### ISSUE THREAD

**Issue by stormstricker** [JakeWharton/flip-tables#21]
When I make the table and print it to console, it works just fine. However when I send the same string to discord as a message, it comes out on the other end with messed spaces between columns.

**Comment by JakeWharton** [comment]
Sounds like the problem is with Discord and not this library then. They could be collapsing adjacent whitespace or using a non-monospaced font, or both. I'm not sure what action I would take to correct this behavior, especially given that it renders correctly in the console where spaces are always preserved and monospace fonts are used.

**Comment by stormstricker** [comment]
I solved it by formatting the result string as code (adding three ticks before and after).
